### ISSUE TITLE
新潮品牌脚本在非node环境执行报错

### ISSUE THREAD

**Issue by ztxtop** [Wenmoux/scripts#2]
需要将taskPostUrl方法的body参数进行encodeURIComponent编码一次才行
PS：估计nodejs发起的请求有对请求参数进行一些处理，所以脚本在qx等工具中跑时，需要将json串的参数进行编码才行

**Comment by Ysnsn** [comment]
@ztxtop 懂

**Comment by Wenmoux** [comment]
@ztxtop 我原本是加了的 后来发现不加也没问题 就tnd删了

**Comment by ztxtop** [comment]
> @ztxtop 我原本是加了的 后来发现不加也没问题 就tnd删了

那修正下，我等着用远程最新脚本呢😄
